### ISSUE TITLE
tempConversion spec doesn't support destructuring

### ISSUE THREAD

**Issue by awkircher** [TheOdinProject/javascript-exercises#110]
It seems like Jasmine doesn't support the syntax:

`const {ftoc, ctof} = require (./tempConversion)`

When trying to test my code, I got a syntax error for the opening `{ `

Changing the syntax to the following fixed the issue:

```
const helpers = require('./tempConversion')
const ftoc = helpers.ftoc
const ctof = helpers.ctof
```

**Comment by twalton83** [comment]
Sorry nobody got back to you! This doesn't appear to be the case, I just tested it and it seems to work just fine. I know it has been a while, but if you could revisit this and perhaps provide a screenshot, that would be great. I can only imagine this would be thrown if the `spec` file was altered, or perhaps one was on a very, very old version of Node, as Node has supported ES6 destructuring for quite some time.
