### ISSUE TITLE
Simon says

### ISSUE THREAD

**Issue by xxerror500xx** [TheOdinProject/javascript-exercises#12]
I noticed that the Simon says exercise was removed from the solutions branch awhile back. I also saw that it is still on the master branch however. I did most of the exercise myself, all the way to the last two specs.

"doesn't capitalize 'little words' in a title", <-- This spec and the one directly after it seemed a bit out of place. They also seem very general and without a great short solution using native js. "little words" just feels subjective and out of scope with the rest of the fairly concise exercise.

Possible options bellow: (I would be happy to make them if you would like)
1. Remove the last two specs from Simon_says on the master branch and Add solutions to the solutions branch.
2. Remove Simon_says from completely from Master and update TOP main curriculum repo. 
https://www.theodinproject.com/courses/web-development-101/lessons/fundamentals-part-5

On a side note I also noticed that Listed in the solutions branch is probably a throwaway file for  	node_modules.

**Comment by codyloyd** [comment]
fixed
