### ISSUE TITLE
What happens if we pass function without first argument as array in "removeFromArray" excersise?

### ISSUE THREAD

**Issue by dainiuxt** [TheOdinProject/javascript-exercises#125]
I tried it and it threw an error. For error handling, I added check `(!array.isArray(arg[0])`, told the function what to do in such situation (I simply returned an empty array) and one additional test 

```
 it('check how it goes when no array passed into', function() {
   expect(removeFromArray("1", 3)).toEqual([]);
 });
```
passed.

**Comment by twalton83** [comment]
This question is a bit unclear. Are you asking if the test *should* pass in this case?

**Comment by dainiuxt** [comment]
@twalton83 , I implemented an error check and added a test to pass. Maybe I can share my solution and test for more clarity (I did tests on my pc only and tested with downloaded Jasmine version, because I can't install any soft on a machine I'm currently using).

My solution:

```
const removeFromArray = function(...args) {
	let array;
	if (!Array.isArray(args[0])) {
		array = [];
	} else {
		array = args[0];
	}
	const newArray = [];
	array.forEach((item) => {
		if (!args.includes(item)) {
			newArray.push(item);
		}
	});
	return newArray;	
}
```
and a test added to check it:
```
 it('check how it goes when no array passed into', function() {
   expect(removeFromArray("1", 3)).toEqual([]);
 });
```
I hope now it is more clear what I would like to say.

**Comment by twalton83** [comment]
I see, but this isn’t the forum to share solutions. I’m glad you were empowered to extend our tests and the solution.

**Comment by dainiuxt** [comment]
Sorry if I posted this in the wrong place. I just trying to absorb new things and need confirmation that I'm going the right way. Maybe it would be better to post this in corresponding discord channel or make a pull request. Thanks for your patience.

**Comment by twalton83** [comment]
Pull requests are to make changes to a repository :) 

I would definitely just discuss this on the Discord channel, but if your tests all pass it's fine. We didn't really intend for you to continue to make your own tests and extend the functionality outside of what was being asked.

**Comment by dainiuxt** [comment]
Noted.
