### ISSUE TITLE
Shift testing library to Jest from Jasmine

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/javascript-exercises#126]
Using a global install of Jasmine is unnecessary because our curriculum doesn't point back to it, and instead points towards libraries like Jest. The process could be simplified for new learners who don't need to rely on a global install and can instead easily just run `npm test`. The failure/successes of each test is also more verbose with Jest by default, which will make new learners more easily know when they are on the right track. 

Completion Criteria:
- [x] Jasmine is removed as a dependency
- [x] Jest is added as a local dependency
- [x] README is rewritten, as well as all other markdown files mentioning Jasmine
- [x] Test syntax is updated from Jasmine to Jest syntax
- [x] All tests in the solutions branch pass

**Comment by xandora** [comment]
I'll take this one on.

**Comment by twalton83** [comment]
Thank you!

**Comment by xandora** [comment]
All requirements are complete. There's an issue with the way the solution branch was spun out of master though, which requires some git wizardry to resolve. Once that's complete I can merge locally, then create a PR for the completed work.
