### ISSUE TITLE
JavaScript terminal

### ISSUE THREAD

**Issue by banCoder** [TheOdinProject/javascript-exercises#13]
Hello, under helloWorld project the README.md says: "Go ahead and run the tests by entering jasmine helloWorld.spec.js in the terminal and watch it fail." I use Visual Studio Code with Windows 10, how am I supposed to do this, why is there no guide on setting up the environment? Thank you.

**Comment by codyloyd** [comment]
Set up instructions are here https://github.com/TheOdinProject/javascript-exercises/blob/master/README.md

Not sure how well it’ll work on windows unless you’re using the Linux subsystem though.  You may have to research installing npm on windows.

**Comment by banCoder** [comment]
Thanks, I'm blind.
