### ISSUE TITLE
../javascript-exercises/caesar/caesar.readme supplemental reading/video provision needed

### ISSUE THREAD

**Issue by datawetenschapper** [TheOdinProject/javascript-exercises#131]
I noticed the Caesar Cipher assignment has a lot of new concepts being introduced without any introductory information being provided in correlation to unicode or regex. 

When googling these topics as a beginner the results are either too technically complex or addressing matters unrelated to the cipher task. 
For unicode I read [this](https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/) to comprehend it, however, [this](https://www.w3schools.com/charsets/ref_html_utf8.asp) might be more succinct and suffice.

For the ruleset to ignore punctuation and spacing I learnt about the RegEx, I saw other students making lists with the alphabet to then loop through whether each iterated element corresponded to their personal list. [This](https://www.youtube.com/watch?v=rhzKDrUiJVk&t) 20 minute video might be useful long term for students to learn during this lesson, perhaps even the assignments prior to it as it would come in handy during the palindrome task as well. The first 10 minutes will be sufficient to complete the task. This also makes you less dependant on random code from stackoverflow without knowing what it actually does.

**Comment by twalton83** [comment]
Sorry for the late response. If we're using unicode, we don't *need* regex to ignore punctuation and spacing (if you check the solution). I support offering more resources for unicode though. That said, we did remove the Caesar Cipher from our lessons, so it is an optional exercise now.

**Comment by I3uckwheat** [comment]
Closing this issue

Stale
Doesn't belong here. 

Consider making an issue in the curriculum repo if this is believed to be an issue.
