### ISSUE TITLE
Clarifying test functions should meet multiple test requirements

### ISSUE THREAD

**Issue by docolius** [TheOdinProject/javascript-exercises#136]
I'm suggesting a note after this line: _'After you pass your first 'it', you will change the next 'xit' to an 'it' and test your code again. You'll do this until all conditions are satisfied.'_ For clarities sake, this means that at the end of each lesson, the single function should satisfy all of the jasmine test requirements at once. 

This could totally be a comprehension issue for me (I'm an artist and English is just barely my first language), but on my first read through I thought I needed to pass all it tests  separately, and even tried to rewrite the test itself for different functions. 

Thankfully a friend of mine who is a programmer (I've been having him review things as I finish them) explained it to me and it all clicked. I re-read the intro's to see if I was just distracted or not comprehending the README. I think that is primarily the case, just figured this addition might help save someone else the same confusion. 

You all rock and thanks for providing/maintaining this material! I've learned far more from these courses than any other source on the net.

**Comment by twalton83** [comment]
Sorry for the late reply. We’ve clarified this in the README! Thanks!
