### ISSUE TITLE
No coding explanations in the solutions branch

### ISSUE THREAD

**Issue by phelpa** [TheOdinProject/javascript-exercises#16]
Could we (odin students) have a detailed explained to what is going on in the code? Sometimes the code looks alien to me, like this one in removeFromArray.js : 

var removeFromArray = function(...args) {
  const array = args[0]
  return array.filter(val => !args.includes(val))
}

I have no idea what "..." , "=>"  , !args does

It looks too advanced from the level where I am at (I am following odin curriculum)

**Comment by achiandet** [comment]
'=>' is an arrow function, '...' is the spread syntax.  Both of these things are ES6 and something we've learned up to this point.

**Comment by aadilayub** [comment]
I had difficulty understanding the solution as well. Not sure if it's just me but I'd never come across array.filter in the teaching materials. I didn't catch the spread syntax bit either until @achiandet pointed it out. It was covered but very briefly. Just sharing my experience.

**Comment by codyloyd** [comment]
you aren't wrong about not seeing that in the content.  My idea in writing those solutions was to give you something to think about and learn with.  I was hoping students would google or ask about things they didn't understand.

HOWEVER, i've gotten this feedback a LOT, so it is obviously something we should either explain more clearly, or just change.

**Comment by codyloyd** [comment]
fixed!
