### ISSUE TITLE
Palindromes bug

### ISSUE THREAD

**Issue by miscany** [TheOdinProject/javascript-exercises#162]
In my solution, I used the function ***string.replaceAll***, which works when I test it myself.
But using the spec.js tester, it says ***"replaceAll is not a `function".***
![pal](https://user-images.githubusercontent.com/84364656/125379452-8a339780-e35e-11eb-8413-8bbc96f9aa65.PNG)
![pal2](https://user-images.githubusercontent.com/84364656/125379470-90c20f00-e35e-11eb-84ab-5ac540362e75.PNG)
### This is a codepen example of the code working
https://codepen.io/miscany/pen/abWBRPb

**Comment by xandora** [comment]
`.replaceAll()` is not a function in Node 14, which is the current LTS version and what we use for all our JavaScript code within TOP.

**Comment by xandora** [comment]
After some research, it looks like your code should work if you replace `.replaceAll()` with just regular ol' `.replace()`, since you're already using a regex, which is one of the requirements for have `.replace()` search for more than the first occurrence of what you want to replace.

**Comment by miscany** [comment]
Smart man! Thanks for pointing that out wow!
