### ISSUE TITLE
Find The Oldest, No Way To Prove Tests

### ISSUE THREAD

**Issue by miscany** [TheOdinProject/javascript-exercises#163]
In Find The Oldest.spec.js, there is no way to prove if someone is still living. In test two  the file only checks the return value of "Ray".
Also, the third test doesn't check if the oldest is still living, it just checks who was sent. Not only would it be pointless to complete these conditions, but I wouldn't even know if I did them correctly lol.

**Comment by twalton83** [comment]
You can certainly prove if someone is still living. I suggest you look at what properties the people in the array have carefully. Ray is the oldest person in the array. Also, the test doesn't *need* to check if the person is still living. That's your job.
