### ISSUE TITLE
leapYears

### ISSUE THREAD

**Issue by nataliacq** [TheOdinProject/javascript-exercises#168]
An alternative solution. 
I used Venn diagrams. Look at this graphic: https://bit.ly/2VrspFB
Where:
   A: numbers divisible by 400
   B: numbers divisible by 100
   C: numbers divisible by 4
We need A and the area between C and B. This can be expressed in set theory as:
(C - B) U A = (C ∩ ¬B) U A
The expression above can be traduced to:
`return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;`
This solution is simplier to explain in this way than the other solution. Both should be considered.
I think explaining this bit of math will make it easier to understand.

**Comment by twalton83** [comment]
I don’t think this is objectively simpler than the existing solution, so I’ll be closing this. Typically, as a heads up, issues are for if something is wrong with the code.
