### ISSUE TITLE
Add numbering on exercise folders

### ISSUE THREAD

**Issue by remtaine** [TheOdinProject/javascript-exercises#169]
It would be more intuitive if the folders were numbered so that they can be done in order. For example, they could be called "01 Hello World", "02 Repeat String", and so on. Their number was mentioned in each of their individual README files, but having the folder themselves labelled doesn't add much effort and makes things easier to go through.

I know the project README says that since it's "still in the process of creating more exercises the order is subject to change and has not yet been specified", but The Odin Project courses already recommend a specific order so I think it can be added on the folder name

**Comment by twalton83** [comment]
Feel free to make the PR to do so 👍🏾
