### ISSUE TITLE
Add arguments to repeatString README

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/javascript-exercises#174]
**Because**: 

A significant amount of students misunderstand the example function call and omit arguments from their solutions, leading to ultimately incorrect code. 

**We should:**
explicitly state the necessary parameters in the README, but tell students that the following exercises will not have the arguments provided so they should read the README and the tests carefully to see what kind of arguments are expected. 

**Acceptance Criteria**:

- [ ] A little blurb stating that the function takes two arguments, `string` and `num`, and an additional mention that the following exercises will not have the arguments provided to them as per the above.

**Comment by msespos** [comment]
I can do this one. Do I need to comment further or should I just go ahead and do it? Thanks!

**Comment by twalton83** [comment]
@msespos Go ahead, thank you :)

**Comment by msespos** [comment]
As I'm doing this, I'm noticing that the bullet points at the bottom of the README are somewhat confusing. It looks like there is an "If..." statement with no "then" followup. My proposed edit is below. Should I include it with this edit or make a separate PR? I'm guessing a separate PR.

Proposed edit:

    If running npm test repeatString.spec.js returns results similar to the below, make sure you have enabled the rest of the tests, as described in the instructions above.
     Test Suites: 1 passed, 1 total
     Tests:       6 skipped, 1 passed, 7 total

What do you think?

**Comment by twalton83** [comment]
It can be the same PR, it's just moving an existing bullet

**Comment by msespos** [comment]
OK thanks!

**Comment by msespos** [comment]
OK both are done and on the same PR. This is my first PR in response to an open issue (all others have been my own suggestions), so let me know if I need to do anything else on my end or if I'm done, please! Thanks! :)
