### ISSUE TITLE
Snakecase solution is problematic

### ISSUE THREAD

**Issue by srr013** [TheOdinProject/javascript-exercises#18]
The snakecase solution ignores the possibility of a word without spaces having multiple upper case characters that should not be separated with an underscore. For example "SnakECase" does not pass.

Just a minor quibble. I love the course!

**Comment by KevinMulhern** [comment]
Great spot with that edge case @srr013. Hopefully someone smarter than me with regex knows of a solution 😆

**Comment by srr013** [comment]
I doubt there's a proper solution to this using regex as the issue stems from understanding how a string breaks down into words. You could implement some sort of dictionary that looks up portions of a string against a database, but that's way outside the scope of this :). I'd suggest just mentioning it in the ReadMe file if this is something worth resolving.

**Comment by KevinMulhern** [comment]
Sounds like a plan, thanks again for pointing this out.

**Comment by codyloyd** [comment]
this is WAY out of the scope of this exercise lol... it's an interesting point, but there's no good solution.
