### ISSUE TITLE
Update repeatString to take alternative strings in tests

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/javascript-exercises#200]
To help avoid students hard coding certain elements of the function, the tests should be updated to pass in a different string for each individual test instead of each test passing in "hey". 

**Completion Criteria:**

- [ ]  Each test in `repeatString.spec.js` has its own unique string that it passes in `eg: repeatString(10, "hello"); repeatString(5, "goodbye")`
- [ ]  The `expect()` is updated to reflect this new string
- [ ]  Test passes
- [ ]  `solutions` and `main` branch both have these changes

**Comment by Maheshkumar-novice** [comment]
I'd love to work on this.

**Comment by twalton83** [comment]
@Maheshkumar-novice assigned.

**Comment by ghost-2362003** [comment]
i would love to work on this
pls assign 
NOW

**Comment by CouchofTomato** [comment]
Go ahead @ghost-2362003

**Comment by ghost-2362003** [comment]
hey @CouchofTomato  i made a mistake 
i accidently forked only the main branch and made the change there 
i am creating a pull request pls take a look asap
ASAP

**Comment by fabulousgk** [comment]
@We-techdesign4u I recomend you join us on discord, lots of help and advice to be had.

**Comment by Luise8** [comment]
Hi, can I work on this?

**Comment by ManonLef** [comment]
It looks like someone else was assigned. @ghost-2362003 any updates? It looks like your previous PR was closed for not filling out the template and required information

**Comment by kumang-subba** [comment]
Hi, can this be assigned to me?

**Comment by CouchofTomato** [comment]
@kumang-subba All yours

**Comment by ghost-2362003** [comment]
hey pls assign me this 
i can help here
