### ISSUE TITLE
A friendly suggestion: we should simplify the unit test for Exercises 01 ~ 07.

### ISSUE THREAD

**Issue by helloShen** [TheOdinProject/javascript-exercises#221]
Since Exercises 01 ~ 07 are faced to beginners.  They are not supposed to use a real-world unit test framework.
To install `Jest`, you have to install a bunch of `nvm`, `node.js`, `npm` at first.  And they have to clone the whole repo, which include critical `package.json` and `pack-lock.json` that unit test depends on. If they just copy `helloWorld.js` and `helloWorld.spec.js` file, it doesn't work.

Although I'm an experienced back-end developer, and have been work with Java `JUnit` for years, it spent me a few hours to install these tools and to figure out how npm work with `Jest` via `package.json` and `pack-lock.json`.

My suggestion is to give them some independent handmade unit test script, for example,
```js
const helloWorld = require('./helloWorld');

function describe(lable, body) {
  console.log(lable);
  body();
}

function test(label, body) {
  if (!body()) console.log(`Failed: ${label}`);
}

describe('Hello World', () => {
  test('says "Hello, World!"', () => {
    expect(helloWorld()).toEqual('Hello, World!');
  });
});
```
Only 2 files `helloWorld.js` and `helloWorld.spec.js` are required, and can be run with 
```bash
node helloWorld.spec.js
```
It can give them an idea of what is unit test actually is, and they will not be scared.

**Comment by twalton83** [comment]
The instructions are pretty well laid out and straightforward and the majority of beginners coming through seem to follow them fine.

**Comment by twalton83** [comment]
I'll be closing because this is a non-issue if one reads the README- there is *very* little that one needs to figure out for themselves because we tell them exactly what they need to know- they don't need to know the in and outs of NPM or Node at this time. And they have been trusted with multiple installations at this point which actually take longer than the handful of steps it takes to set this up.

**Comment by helloShen** [comment]
Fine:)

> I'll be closing because this is a non-issue if one reads the README- there is _very_ little that one needs to figure out for themselves because we tell them exactly what they need to know- they don't need to know the in and outs of NPM or Node at this time. And they have been trusted with multiple installations at this point which actually take longer than the handful of steps it takes to set this up. The Git setup is more in depth than this and has more steps to follow, as well as the virtual machine and dual boot.
