### ISSUE TITLE
10_fibonacci: add test for fibonacci(0)

### ISSUE THREAD

**Issue by LedaThemis** [TheOdinProject/javascript-exercises#236]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Exercises: Add exercise on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The current accepted solution has a check for fibonacci(0) which equals 0
<details>
<summary>Spoiler</summary>
<code>if (count === 0) return 0;</code>
</details>

But the provided tests doesn't check for this case, so a student can implement the fibonacci function by using the following logic:
```js
if (n===1 || n===2) return 1;
```
and it would pass all the tests.

That's why I think a test for `fibonacci(0)` is necessary.

**2. Acceptance Criteria:**

- [ ] Add a check for fibonacci(0)

**Comment by Keerthivardhan1** [comment]
fibonacci(0) is 0 right

**Comment by Keerthivardhan1** [comment]
so can I add one more condition 
if (n==0) return 0;

**Comment by Keerthivardhan1** [comment]
if it is correct can I solve this issue

**Comment by elite16op** [comment]
Can I take up this issue ?

**Comment by KelvinMvungi** [comment]
From the solution the strict equality `count === 0` throws an error in the test, for a 0 as string as shown ----> `fibonacci("0")`

**Comment by LedaThemis** [comment]
This was addressed in #357, Closing.
