### ISSUE TITLE
Trivial non-important typo in 02_repeatString > repeatString.spec.js

### ISSUE THREAD

**Issue by MasQueElite** [TheOdinProject/javascript-exercises#240]
*Line 32:* `(...).match(/((hey))/g).length).(...)`
*Should be:* `(...).match(/(hey)/g).length).(...)`

*Reason:* You are already capturing a group.

**Comment by deveshidwivedi** [comment]
hi can i fix this?

**Comment by thatblindgeye** [comment]
@deveshidwivedi are you still interested in working on this?
