### ISSUE TITLE
NPM Vulnerabilities Warning

### ISSUE THREAD

**Issue by ArcaneIRE** [TheOdinProject/javascript-exercises#250]
After running `npm install` as directed in the readme, I was shown a 'vulnerability' warning.
![Screenshot from 2022-05-14 13-46-42](https://user-images.githubusercontent.com/44246360/168426361-e984c98f-ca43-48e3-a355-a702624b90ab.png)

From [what I can gather](https://www.voitanos.io/blog/don-t-be-alarmed-by-vulnerabilities-after-running-npm-install/), I'm supposed to ignore these. However, a 'critical' warning implies that it should be attended to. 

Since this is the first use of `npm install` in the course, maybe it would be a good idea to add a mention of the audit feature the readme?

**Comment by Mahir1015** [comment]
The vulnerabilities can be audited and fixed by running the command 'npm audit fix'. Can you please assign it to me so that I can update the readme for the following issue?

**Comment by ManonLef** [comment]
anyone of the @TheOdinProject/javascript maintainers team that could have a look at this?

**Comment by fabulousgk** [comment]
Any feedback on this?

**Comment by wise-king-sullyman** [comment]
@fabulousgk's plan sounds good to me
