### ISSUE TITLE
Bug - 04_removeFromArray: missing test case

### ISSUE THREAD

**Issue by Sarthak-Malla** [TheOdinProject/javascript-exercises#271]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Exercises: File type incorrect for all test files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The testing for the solution has a missing test case that looks into if all the elements in the Array that matches the element to be deleted is properly deleted.

In other words, the Array from which the elements are supposed to be deleted from has no repeating values. So, the test case does not directly prompt the user to write code that deletes all the instances of the element that is supposed to be deleted from the Array.

**2. How To Reproduce:**

<ul>
<li> Write the code that satisfies all the 7 cases in the 04_removeFromArray exercise.
<li> Open the `removeFromArray.spec.js` file and modify the 5th test case such that the initial array has [1, 2, 2, 3, 4]
<li> Run the code again.
</ul>

**3. Expected Behavior:**

If the code written does not account for repeated values like the one below, the modified test case (5th test case) results to a failure.
```
const removeFromArray = function(...arg) {
    const arr = arg[0];
    arg.splice(0,1);

    for (let i = 0; i < arg.length; i++) {
        for (let j = 0; j < arr.length; j++) {
            if (arg[i] === arr[j]) {
                arr.splice(j, 1);
                // j--;
            }
        }
    }

    return arr;
};
```
*Note:* Line 9 is commented such that the test case is not matched!

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by thatblindgeye** [comment]
@Sarthak-Malla would you still be interested in working on this?

**Comment by thatblindgeye** [comment]
@Sarthak-Malla We'd need a new test added to both the `removeFromArray.spec.js` file as well as the solution's `removeFromArray-solution.spec.js` file. For the normal spec.js file the test should be skipped. We could just copy+paste one of the existing tests and tweak it to something like:

```javascript
test.skip('removes all instances of a value', () => {
  expect(removeFromArray([1, 2, 2, 3], 2)).toEqual([1, 3]);
});
```

Or however you think makes sense to write the test.

**Comment by thatblindgeye** [comment]
@Sarthak-Malla just checking in on the status of this

**Comment by Sarthak-Malla** [comment]
@thatblindgeye  Hey, I am really sorry. I am caught in load of work, is it possible to re-assign this to someone else?

**Comment by shubhatRashid** [comment]
hey,
just checked the code and i think its working exactly as expected. There doesnot seem to be any issue . The fifth test case does fail after modification of the input and only passed when we take into acount the repeacting occurance .Hope you guys check it again and if there still is any issue please describe it so that it is more clear.

**Comment by thatblindgeye** [comment]
Looks like such a test case was added after this issue was created. Closing this out, but thank you for bringing this up!

**Comment by shubhatRashid** [comment]
No problem,
Although that would mean i would be Still looking for my first good issue 
😅...

**Comment by thatblindgeye** [comment]
@shubhatRashid it doesn't have the label, but https://github.com/TheOdinProject/javascript-exercises/issues/255 might actually be a decent first issue if you'd wanna check that out?
