### ISSUE TITLE
Bug - : tempConversion: Doesn't skip test cases

### ISSUE THREAD

**Issue by Lomlomm** [TheOdinProject/javascript-exercises#318]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Exercises: File type incorrect for all test files`

The following checkbox is OPTIONAL:

- [x] I would like to be assigned this issue to work on it

<hr>

** Description of the Bug:**
The first time I run the code with the 'npm test tempConversion.spec.js' it should only test it with those test cases that doesn't have de '.skip' method. Right now the code its been test with all the test cases even though they have the '.skip' method

** Desktop/Device:**

-   Device: MacBook Air
-   OS: MacOS Mojave 10.14.5

**Comment by thatblindgeye** [comment]
@Lomlomm can you confirm that you're still seeing this issue?

**Comment by thatblindgeye** [comment]
Going to close this due to no response and unable to reproduce this issue. Trying to test specifically the tempConversion exercise and tests are being skipped fine for me on a Mac.
