### ISSUE TITLE
Fundamentals Part 2, Exercise 3: Instructions Rewrite

### ISSUE THREAD

**Issue by maleker86** [TheOdinProject/javascript-exercises#353]
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Exercises: Add exercise on XYZ`

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
The instructions for math.js are easily misinterpreted: 
```
* Some rules first:
 *   Enter the operations, replacing the `"?"`, make the computer do the work for you. 
 *   Do not manually enter the answer, for example: "one plus ten" would look like 1+10
```
Namely, "Do not manually enter the answer, for example..." Grammatically, what follows "for example" is _manually entered content_ that is **not permissible**. Please rework to indicate that the exercise **does** need a solution that would like like 1+10... <br> 
Otherwise, the instructions ask us to provide an operator without operands (the "?" is one character, the student expecting to provide one character only to replace it), which, with the provided code, will not ever produce the correct / desired solution. 

**2. Acceptance Criteria:**
- [ ] Instructions do not discourage and encourage in the same line
- [ ] Updated instructions are pushed to Replit
 

**3. Additional Information:**
Lesson: https://www.theodinproject.com/lessons/foundations-fundamentals-part-2
Replit: https://replit.com/@OdinProject/lets-do-some-math#math.js

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript

**Comment by wise-king-sullyman** [comment]
Thanks for putting up this issue @maleker86.

The replit content isn't editable via PR, but if someone has a suggestion for something that's more clear leave it here and a member of the maintainer team should be able to update it.

**Comment by thatblindgeye** [comment]
We could update the Replit to be more along the lines of:

```
/**
 * Lets do some math!
 * Some rules first:
 *   - Replace the string values for each variable with the corresponding math equation
 *   - Do not manually enter the answers to the equations. For example, `const a = 9` would be incorrect as 9 is the answer to the equation you're being asked to write out
 */

const a = "one plus eight"
const b = "22 times three"
const c = "the *remainder* of 5/4"
const d = "the variable 'a' minus 17"
const e = "the sum of the previous four variables"

module.exports = {a, b, c, d, e}
```

At the very least putting the "questions" inline with the variable declarations requires less having to look up and down.

**Comment by marlatte** [comment]
Another option with fewer changes:

`* Some rules first:
  *   Replace the `"?"` with the correct math expression.
  *   Do NOT manually enter the answer. Make the computer do the work for you. 
  *   For example: if given "one plus ten," you would rewrite it to 1 + 10. Don't just write in 11.`


Although I also like @thatblindgeye 's suggestion of reducing the total number of lines. If you go with that, might I recommend the first line of the rules be:

`Replace the strings to the right of the = with the math expression they describe.`

**Comment by wise-king-sullyman** [comment]
I've updated it with a combination of the above suggestions, is everyone happy with what's there now?

**Comment by thatblindgeye** [comment]
@wise-king-sullyman ++

@maleker86 what do you think of the latest update to the Replit?

**Comment by thatblindgeye** [comment]
Closing as updates were made
