### ISSUE TITLE
Fix unclear functionality definition in 09_palindromes

### ISSUE THREAD

**Issue by SoulmongerV2** [TheOdinProject/javascript-exercises#355]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Exercises: Add exercise on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**<br>
The final test requires the function to work with numbers in the argument string, the solution however ignores numbers completely, flagging strings such as "123racecar" as palindromes.

**2. Acceptance Criteria:**<br>
- [ ] Specify that numbers are to be ignored by the function's logic in the README.md
or 
- [ ] Alter the solution to support numerical palindromes.

**3. Additional Information:**

**Comment by codyloyd** [comment]
fixed by #357
