### ISSUE TITLE
07_tempConversion: task needs rephrasing regarding module.exports

### ISSUE THREAD

**Issue by theaiyoh** [TheOdinProject/javascript-exercises#388]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Exercises: Add exercise on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

In the current README for the task 07_tempConversion it says:

_"This exercise asks you to create more than one function so the `module.exports` section of the spec file looks a little different this time."_

The module.exports is not in the spec or test file, rather in the main .js file where the code by the student needs to be written. I think this will cause confusion for the beginner because in a previous task it's mentioned that require statements are in the .spec files and module.exports is in the main .js file. Needs rephrasing to something like this:

_"This exercise asks you to create more than one function so the `module.exports` section of the main javascript file looks a little different this time."_

**2. Acceptance Criteria:**

- [ ] Slight rephrase of the sentence mentioned above

**3. Additional Information:**

None.

**Comment by wise-king-sullyman** [comment]
Seems like a solid suggestion to me, would you like to make this change?

**Comment by theaiyoh** [comment]
I made a pull request and linked it to this issue

**Comment by thatblindgeye** [comment]
@theaiyoh did you still want to work on this? Looks like your branch was deleted so the PR got closed out.

**Comment by thatblindgeye** [comment]
Gonna open this up to others to contribute

**Comment by manny53365** [comment]
@thatblindgeye - Could I be assigned?
