### ISSUE TITLE
Bug - in the authentication basics at the bcrypt.hash function the first argument says "somePassword" which makes it seem like its for a string to name the hash or something when instead it should say req.body.password as that is how the tutorials index.ejs forms password input is setup with name passord :

### ISSUE THREAD

**Issue by pethoburr** [TheOdinProject/javascript-exercises#395]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Exercises: File type incorrect for all test files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

in the authentication basics at the bcrypt.hash function the first argument says "somePassword" which makes it seem like its for a string to name the hash or something when instead it should say req.body.password as that is how the tutorials index.ejs forms password input is setup with name passord 

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: Ubuntu VM 
-   OS: Linux
-   Browser: Chrome
-   Version: 

**5. Additional Information:**
its confusing as it doesnt say to replace "somePassword" with req.body.password or to replace it at all it just says to add that function in

**Comment by MaoShizhong** [comment]
Looks like this should be addressed if [#26202 from the curriculum repo](https://github.com/TheOdinProject/curriculum/pull/26202) is merged.

**Comment by pethoburr** [comment]
Awesome, thanks!
