### ISSUE TITLE
05_sumAll - Add alternative solution using Gauss formula

### ISSUE THREAD

**Issue by oomertaa** [TheOdinProject/javascript-exercises#431]
Complete the following REQUIRED checkboxes:
-   [ X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ X] The title of this issue follows the `location for request: brief description of request` format, e.g. `Exercises: Add exercise on XYZ`

The following checkbox is OPTIONAL:

-   [ X] I would like to be assigned this issue to work on it - Yes, but I don't know how i would be able to add to the official repo.

<hr>

**1. Description of the Feature Request:**

**2. Acceptance Criteria:**

**3. Additional Information:**
![Screenshot_1](https://github.com/TheOdinProject/javascript-exercises/assets/111696203/ffba7cd2-4455-458e-8e92-fc051c4d45c8)

**Comment by thatblindgeye** [comment]
While this additional solution is helpful from a maths standpoint, I don't think it offers significant benefit from the intent of the exercise, which is to practice writing unit tests.
