### ISSUE TITLE
Tests: Refactor Jest tests to Node.js test runner

### ISSUE THREAD

**Issue by cakegod** [TheOdinProject/javascript-exercises#486]
### Pre-requisites
Please complete the following REQUIRED checkboxes:
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md).
- [x] The title of this issue follows the `location for request: brief description of request` format, e.g., `Exercises: Add exercise on XYZ`.

The following checkbox is OPTIONAL:

- [x] I would like to be assigned this issue to work on it.

<hr>

### 1. Description of the Feature Request
I propose refactoring our tests from Jest to the Node test runner, which has been stable since [Node v20](https://nodejs.org/en/blog/announcements/v20-release-announce#stable-test-runner). This transition can reduce our dependencies and potentially improve maintainability as the test runner is directly integrated into the Node runtime. 

Additionally, but anecdotally, Node test runner is more than three times faster on my old PC. 

### 2. Acceptance Criteria

- [ ] All existing Jest tests refactored to use the Node.js test runner.
- [ ] Ensure all refactored tests pass successfully.
- [ ] Update any relevant documentation to reflect the change in test runner.

**Comment by MaoShizhong** [comment]
Thanks for the suggestion. Had a chat as a team and this is something we felt was not really necessary to change at this point.
