### ISSUE TITLE
Refactor existing issue templates the new YAML issue template format

### ISSUE THREAD

**Issue by cakegod** [TheOdinProject/javascript-exercises#487]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Exercises: Add exercise on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
I propose merging our two existing issue templates into a single template using the new YAML issue template format. This new unified template will simplify the process of creating a new issue and will be similar to the one used in the curriculum repo.

**2. Acceptance Criteria:**

- [ ] Refactor the two existing issue templates into the new YAML issue template.

**Comment by MaoShizhong** [comment]
I'm not sure it's so necessary to combine into 1 issue template like the curriculum one. Most of the other repos have split templates for bug report/feature request etc.

*But* converting from noisy markdown issue templates to issue forms via the yaml format does sound sensible, and other repos already use the yaml format. Very happy for the two templates to be converted to this.

**Comment by cakegod** [comment]
That sounds sensible. I'll convert them.
