### ISSUE TITLE
Exercises should be contained separately if they are not done in the same lesson.

### ISSUE THREAD

**Issue by minimalsm** [TheOdinProject/javascript-exercises#71]
I was doing these for JS Fundamentals 4, when I cloned the repo I had to look forward in the curriculum to make sure that the additional exercises contained in the repo were issued in a later lesson. 

My first thought was that more exercises had been added for the sake of rigor but the page hadn't been updated.

https://www.theodinproject.com/courses/web-development-101/lessons/fundamentals-part-4

**Comment by minimalsm** [comment]
It would also make more sense if exercises were numbered otherwise you have to needlessly switch between code editor and browser to see what exercise you have to complete next.

**Comment by twalton83** [comment]
Closed because we have now numbered the exercises in #169
