### ISSUE TITLE
repeatString test should check for random inputs

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/javascript-exercises#72]
In [this test](https://github.com/TheOdinProject/javascript-exercises/tree/master/repeatString) a new test should be added that inputs random numbers to help prevent hard-coding solutions. 

There should also be some comments explaining the random number generation.

One should use regex to verify the return value of repeatString called with a random input. Regex should be used to prevent giving away a solution.

A solution for the regex is below: 

```js
"function return value".match(/((hey))/).length === random number
```

This is for first-time contributors only

**Comment by teensyPython** [comment]
Is using a for loop necessary? Can I use String.prototype.repeat() method ?

**Comment by I3uckwheat** [comment]
> Is using a loop necessary? Can I use String.prototype.repeat() method ?

@teensyPython This is not a place for help, please try the discord channel. You can find a link on the website, under the "community" tab.

**Comment by Timework** [comment]
I would like to take care of this one if that's ok, looks like something I can do with my current ability.
