### ISSUE TITLE
Palindrome exercise

### ISSUE THREAD

**Issue by Galexy5** [TheOdinProject/javascript-exercises#75]
In palindrome exercise the strings with dot [.] at the end shouldn't be false ? I think its more accurate this way, maybe.
Thank you

**Comment by imrogerjiang** [comment]
Are you referring to
`expect(palindromes('ZZZZ car, a man, a maraca.')).toEqual(false);`

It's false not because of the . but because of the ZZZZ at the start of the string.

**Comment by Galexy5** [comment]
I was talking about the others too but I just saw that the second one has to work with punctuation . Didn't see that before I just assumed it was for caps.
So just curious, if I wanted to solve punctuation too I should check a letter regex at string(-1) and if is not a letter remove it ?I Is that a good way to solve it ?
