### ISSUE TITLE
javascript-exercises/solutions/sumAll - order of exception checks

### ISSUE THREAD

**Issue by 17wilsonb** [TheOdinProject/javascript-exercises#79]
Looking at the solution file for sumAll, shouldn't the exception check for the `typeof` the inputs be done before checking if the inputs are greater than 0?

For example, if the user passes in sumAll("-1", 2) and the exception check to see if they are both above 0 is done first, the exception may not check it correctly. Checking the `typeof` each to ensure they are both numbers before making sure they are both positive would flow more logically.

**Comment by Musabii** [comment]
@17wilsonb it doesn't check if both are above 0 it checks if either one of them is below 0. but I agree it would flow better logically if we checked if they are numbers first. doesn't really matter though.

**Comment by twalton83** [comment]
Closing because it is a stale issue.
