### ISSUE TITLE
No specs found

### ISSUE THREAD

**Issue by LutherCalvinRiggs** [TheOdinProject/javascript-exercises#97]
This is regarding the repeatString exercise.

I finished Hello,World and it worked fine. 

When i moved on to repeatString i kept getting 'No specs found'. Eventually I copied/pasted the answer code into the test to make sure everything was working right with the computer and I still get back 'No specs found' 

Is there anyone able to guide me on what to do next to fix this problem?

Thank you!

**Comment by ssmith0185** [comment]
> 
> 
> This is regarding the repeatString exercise.
> 
> I finished Hello,World and it worked fine.
> 
> When i moved on to repeatString i kept getting 'No specs found'. Eventually I copied/pasted the answer code into the test to make sure everything was working right with the computer and I still get back 'No specs found'
> 
> Is there anyone able to guide me on what to do next to fix this problem?
> 
> Thank you!

Did you try switching to the "repeatString" directory? I had that same issue until I switched directories.
